apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
data:
  password: {{ .Values.kafka.password | b64enc }}
  username: {{ .Values.kafka.username | b64enc }}